ports:
  midi:
    out:
      - "AudioBox USB 96" # "IAC Driver Internal MIDI"
    in:
      - "Midi Fighter Twister"
      - "nanoKEY2 KEYBOARD"
  grid: "/dev/ttyUSB0" #"/dev/tty.usbserial-m1000843"

layouts:
  sequencer:
    layout_file: "sequencer/layout.yml"
  pattern:
    layout_file: "pattern/layout.yml"

instruments:
  er1: "er1/config.yml"
  # juno60: "juno60/config.yml"
  # sp404:
  #   layout_file: "sp404_layout.yml"
  # ms20:
  #   layout_file: "ms20_layout.yml"
  # gr1:
  #   chan: 10
  #   layout_file: "gr1_layout.yml"
  # microgranny:
  #   layout_file: "microgranny_layout.yml"

controllers:
  - nanokey
  - glove
